"""User last seen

Revision ID: 386555779d3b
Revises: 00e650e7cc35
Create Date: 2020-04-29 13:55:48.924648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386555779d3b'
down_revision = '00e650e7cc35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False))
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###
